services:
  # mongodb2:
  #   image: mongo:latest
  #   container_name: mongodb_container
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db

  # mongo-express:
  #   image: mongo-express:latest
  #   container_name: mongodb_visualizer
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongodb2
  #     - ME_CONFIG_BASICAUTH_USERNAME=admin
  #     - ME_CONFIG_BASICAUTH_PASSWORD=pass
  #   depends_on:
  #     - mongodb2

  service-recommandation:
    build: .
    container_name: service_recommandation
    # environment:
    #   - MONGO_URL=mongodb://mongodb2:27017/recommandation
    # depends_on:
    #   - mongodb2
    ports:
      - "3001:3001"

volumes:
  mongo_data: